export const GET_RECIPES= 'GET_RECIPES'
export const GET_RECIPES_OKEY= 'GET_RECIPES_EXITO'
export const GET_RECIPES_ERROR= 'GET_RECIPES_ERROR'


export const SEARCH_RECIPES= 'SEARCH_RECIPES'
export const SEARCH_RECIPES_OKEY= 'SEARCH_RECIPES_EXITO'
export const SEARCH_RECIPES_ERROR= 'SEARCH_RECIPES_ERROR'


export const FILTER_RECIPES= 'FILTER_RECIPES'
export const FILTER_RECIPES_RESET= 'FILTER_RECIPES_RESET'

export const ORDER_BY_NAME= 'ORDER_BY_NAME'
export const ORDER_BY_SCORE= 'ORDER_BY_SCORE'
export const ORDER_BY_HEALTH_SCORE= 'ORDER_BY_HEALTH_SCORE'
export const ORDER_BY_LIKES= 'ORDER_BY_LIKES'
export const ORDER_BY_TIME_PREPARATION= 'ORDER_BY_TIME_PREPARATION'


export const RESET_ERROR= 'RESET_ERROR'


export const GET_FILTER= 'GET_FILTER'
export const GET_FILTER_OKEY= 'GET_FILTER_OKEY'
export const GET_FILTER_ERROR= 'GET_FILTER_ERROR'

export const GET_BY_ID= 'GET_BY_ID'
export const GET_BY_ID_OKEY= 'GET_BY_ID_OKEY'
export const GET_BY_ID_ERROR= 'GET_BY_ID_ERROR'