export const GET_RECIPES= 'GET_RECIPES'
export const GET_RECIPES_OKEY= 'GET_RECIPES_EXITO'
export const GET_RECIPES_ERROR= 'GET_RECIPES_ERROR'


export const SEARCH_RECIPES= 'SEARCH_RECIPES'
export const SEARCH_RECIPES_OKEY= 'SEARCH_RECIPES_EXITO'
export const SEARCH_RECIPES_ERROR= 'SEARCH_RECIPES_ERROR'



export const FILTER_RECIPES= 'FILTER_RECIPES'
export const FILTER_RECIPES_RESET= 'FILTER_RECIPES_RESET'


export const GET_FILTER= 'GET_FILTER'
export const GET_FILTER_OKEY= 'GET_FILTER_OKEY'
export const GET_FILTER_ERROR= 'GET_FILTER_ERROR'
